### ISSUE TITLE
Remove "mi" From Canvas

### ISSUE THREAD

**Issue by simondueckert** [simondueckert/lernos#11]
The personal Canvas will just be named "lernOS Canvas". Other variants might be named "lernOS Canvas for Teams" etc. Renaming has to be done in ppt, pdf, png and in the folder structure.

**Comment by lootsy** [comment]
I will give this topic a try.
Pull request is (ASAP) on it's way.

**Comment by lootsy** [comment]
I don't know how to handle these files:

* 'lernOS Guide - en'\lernOS-mi-Canvas.pdf
* 'lernOS Guide - en'\lernOS-mi-Canvas.png

because there are already files without "mi" in the folder.
And it seems that their content isn't the same.

**Comment by simondueckert** [comment]
Yes, I have to clean this up. I removed the "mi" from the canvas name and I have to do that in the file names as well. I also want to have a clean folder structure in terms of lernOS elements, language versions and file formats. Plan to think about it after [the open web session 2018-7-9 from 4-5pm CEST](https://zoom.us/j/497571515).

**Comment by lootsy** [comment]
Ok, don't wanna confuse.

I saw your milestone 0.6. Therefore I thought it should be done _before_ your web session.
I'll try to attend.

**Comment by simondueckert** [comment]
Done.
