### ISSUE TITLE
Add EU DigiComp to lernOS

### ISSUE THREAD

**Issue by simondueckert** [simondueckert/lernos#15]
Suggested by @martinlindner: make lernOS compatible with [DigComp 2.1: The Digital Competence Framework for Citizens with eight proficiency levels and examples of use](https://ec.europa.eu/jrc/en/publication/eur-scientific-and-technical-research-reports/digcomp-21-digital-competence-framework-citizens-eight-proficiency-levels-and-examples-use). It can be used instead of or in addition to Mozilla Web Literacy Framework (Digital Literacy vs. Web Literacy).

**Comment by simondueckert** [comment]
We could use the [cryptoparty handbook](https://www.cryptoparty.in/learn/handbook) for comptetence area 4 “Safety”.

**Comment by simondueckert** [comment]
A visual self check test like [this one](https://digital-competence.eu) could be added ...

**Comment by simondueckert** [comment]
[Reuse policy of EU documents](https://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2011:330:0039:0042:EN:PDF) has to be considered.

**Comment by jurijmlotman** [comment]
Reuse: Das ist von 2012. Bereits 5 Jahre (2017) später sagen sie dies: "EU publications
Reuse of information managed by the Publications Office of the Europan Union
Publication metadata

The Publications Office is at the forefront of the implementation of the reuse policy of the European Commission, as set out in Commission Decision 2011/833/EU on the reuse of Commission documents. Under this policy anyone can reuse Commission information free of charge and without having to request permission to do so. Information can be reused both for commercial and non-commercial purposes. In this context the Publications Office enables reuse of EU information in different ways. Interested parties can simply download the required documents from the relevant websites managed by the Publications Office and then proceed with their reuse."  https://publications.europa.eu/en/publication-detail/-/publication/aa9de27b-b85a-11e6-9e3c-01aa75ed71a1/language-en

**Comment by simondueckert** [comment]
Replaced by #24
