### ISSUE TITLE
Test Automatic Translation

### ISSUE THREAD

**Issue by simondueckert** [simondueckert/lernos#7]
Test chain MD (en) to HTML (en) to multilanguage PDF.

**Comment by lootsy** [comment]
How do you produce the multilingual documents?
Which chain do you use?

Is there a need to put it in the cloud? (something like, a commit starts the preparation of the several documents?

**Comment by simondueckert** [comment]
No fully automated chain yet. I found nothing to translate markdown sources so far. There are several possibilities I want to test in the near future:

1. Markdown (en) -> HTML (en) with Google Translator Toolkit -> HTML (other languages) -> other Formats (Word, PDF, Wiki, epub etc.)
1. Testing translation via [DeepL API](https://www.deepl.com/api.html) vs. Google results
1. Using [contolled natural language](https://en.m.wikipedia.org/wiki/Controlled_natural_language) to get better results from automatic translation

**Comment by simondueckert** [comment]
Perhaps simplified technical english (STE) could help to translate automatically. Specification ASD-STE100 ([PDF](https://guiseppegetto.com/pwr393/wp-content/uploads/2013/02/ASD-STE100-ISSUE-6.pdf)).

**Comment by lootsy** [comment]
I had a short view at STE. At the beginning this approach might be useful. However if lernOS will evolve I think this type of language will be too in-emotional.

I think the emotional part is crucial for developing your mindset.

Just my 2 ct

**Comment by simondueckert** [comment]
Might be true. I tested the automatic translation with DeepL. I optimized the chapter “Why lernOS?” a little bit and translation en->de looks quite good. Perhaps we do not need too much simplification in the language.

**Comment by lootsy** [comment]
I never tried DeepL but read / heared some parts about it. Everybody was astonished. ;)

I would go this way: Clearly state at the begin of the text: this text is translated by a machine.
If it is not revised by an human being.

In the long run: I would look for a godfather for each (supported) translation.

**Comment by simondueckert** [comment]
Office 365 translator API: 
https://www.microsoft.com/en-us/translator/word.aspx

**Comment by simondueckert** [comment]
Languages by number of native speakers: 
https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers

**Comment by simondueckert** [comment]
Results of translation test with microsoft translator en->de and en->es:

- technical terms are translated (e.g. lernOS Circle -> lernOS-Zirkel)
- Mistakes with uppercase/lowercase
- Problems with translating english "you" (Sie, Du, Usted)
- Mistakes (e.g. necessary->NEC)
